using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DesktopNutritionTracker.Models;

namespace DesktopNutritionTracker.Reports
{
    public partial class WeeklyReportTemplate
    {
        // Properties used in the T4 Template
        public string StartDate { get; set; } = "";
        public string EndDate { get; set; } = "";
        public string ProfileName { get; set; } = "Standard Baseline";
        public string BiologicalSex { get; set; } = "";
        public int Age { get; set; } = 30;
        public string ActivityLevel { get; set; } = "Lightly Active";

        // Dashboard average metrics
        public double AvgCalories { get; set; }
        public double AvgProtein { get; set; }
        public double AvgCarbs { get; set; }
        public double AvgFat { get; set; }
        public double AvgWater { get; set; }

        // Core data lists
        public List<NutrientStatus> WeeklyNutrientStatuses { get; set; } = new List<NutrientStatus>();
        public List<FoodLogEntry> WeeklyFoodLogs { get; set; } = new List<FoodLogEntry>();

        /// <summary>
        /// Generates the HTML report contents using the template design.
        /// </summary>
        public string TransformText()
        {
            var sb = new StringBuilder();

            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html lang=\"en\">");
            sb.AppendLine("<head>");
            sb.AppendLine("    <meta charset=\"UTF-8\">");
            sb.AppendLine("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
            sb.AppendLine("    <title>NutriScribe Clinical Weekly Progress Report</title>");
            sb.AppendLine("    <!-- Include Chart.js CDN for interactive visual analytics -->");
            sb.AppendLine("    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>");
            sb.AppendLine("    <style>");
            sb.AppendLine("        :root {");
            sb.AppendLine("            --bg-color: #0b0f19;");
            sb.AppendLine("            --card-bg: #151f32;");
            sb.AppendLine("            --primary: #38bdf8;");
            sb.AppendLine("            --text: #f8fafc;");
            sb.AppendLine("            --text-secondary: #94a3b8;");
            sb.AppendLine("            --border: #24354f;");
            sb.AppendLine("            --success: #10b981;");
            sb.AppendLine("            --warning: #f59e0b;");
            sb.AppendLine("            --danger: #ef4444;");
            sb.AppendLine("            --accent-glow: rgba(56, 189, 248, 0.15);");
            sb.AppendLine("        }");
            sb.AppendLine("        body {");
            sb.AppendLine("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;");
            sb.AppendLine("            background-color: var(--bg-color);");
            sb.AppendLine("            color: var(--text);");
            sb.AppendLine("            margin: 0;");
            sb.AppendLine("            padding: 32px;");
            sb.AppendLine("            line-height: 1.6;");
            sb.AppendLine("        }");
            sb.AppendLine("        .container {");
            sb.AppendLine("            max-width: 1100px;");
            sb.AppendLine("            margin: 0 auto;");
            sb.AppendLine("        }");
            sb.AppendLine("        .header {");
            sb.AppendLine("            text-align: center;");
            sb.AppendLine("            padding: 40px 24px;");
            sb.AppendLine("            background: linear-gradient(135deg, #151f32 0%, #0b0f19 100%);");
            sb.AppendLine("            border: 1px solid var(--border);");
            sb.AppendLine("            border-radius: 16px;");
            sb.AppendLine("            margin-bottom: 28px;");
            sb.AppendLine("            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.25);");
            sb.AppendLine("        }");
            sb.AppendLine("        .header h1 {");
            sb.AppendLine("            margin: 0 0 8px 0;");
            sb.AppendLine("            color: var(--primary);");
            sb.AppendLine("            font-size: 2.5rem;");
            sb.AppendLine("            letter-spacing: 1.5px;");
            sb.AppendLine("            font-weight: 800;");
            sb.AppendLine("        }");
            sb.AppendLine("        .header p {");
            sb.AppendLine("            margin: 0;");
            sb.AppendLine("            color: var(--text-secondary);");
            sb.AppendLine("            font-size: 1.1rem;");
            sb.AppendLine("        }");
            sb.AppendLine("        .meta-grid {");
            sb.AppendLine("            display: grid;");
            sb.AppendLine("            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));");
            sb.AppendLine("            gap: 16px;");
            sb.AppendLine("            margin-top: 32px;");
            sb.AppendLine("        }");
            sb.AppendLine("        .meta-card {");
            sb.AppendLine("            background: rgba(255, 255, 255, 0.02);");
            sb.AppendLine("            border: 1px solid var(--border);");
            sb.AppendLine("            padding: 16px;");
            sb.AppendLine("            border-radius: 10px;");
            sb.AppendLine("            text-align: center;");
            sb.AppendLine("            transition: all 0.3s ease;");
            sb.AppendLine("        }");
            sb.AppendLine("        .meta-card:hover {");
            sb.AppendLine("            border-color: var(--primary);");
            sb.AppendLine("            box-shadow: 0 0 12px var(--accent-glow);");
            sb.AppendLine("        }");
            sb.AppendLine("        .meta-card .label {");
            sb.AppendLine("            font-size: 0.75rem;");
            sb.AppendLine("            color: var(--text-secondary);");
            sb.AppendLine("            text-transform: uppercase;");
            sb.AppendLine("            margin-bottom: 6px;");
            sb.AppendLine("            letter-spacing: 0.5px;");
            sb.AppendLine("        }");
            sb.AppendLine("        .meta-card .value {");
            sb.AppendLine("            font-size: 1.25rem;");
            sb.AppendLine("            font-weight: bold;");
            sb.AppendLine("            color: var(--text);");
            sb.AppendLine("        }");
            sb.AppendLine("        .section-card {");
            sb.AppendLine("            background-color: var(--card-bg);");
            sb.AppendLine("            border: 1px solid var(--border);");
            sb.AppendLine("            border-radius: 16px;");
            sb.AppendLine("            padding: 32px;");
            sb.AppendLine("            margin-bottom: 28px;");
            sb.AppendLine("            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.15);");
            sb.AppendLine("        }");
            sb.AppendLine("        .section-card h2 {");
            sb.AppendLine("            margin-top: 0;");
            sb.AppendLine("            margin-bottom: 20px;");
            sb.AppendLine("            font-size: 1.5rem;");
            sb.AppendLine("            border-bottom: 2px solid var(--border);");
            sb.AppendLine("            padding-bottom: 12px;");
            sb.AppendLine("            color: var(--primary);");
            sb.AppendLine("            font-weight: 700;");
            sb.AppendLine("            display: flex;");
            sb.AppendLine("            align-items: center;");
            sb.AppendLine("            gap: 10px;");
            sb.AppendLine("        }");
            sb.AppendLine("        .overview-grid {");
            sb.AppendLine("            display: grid;");
            sb.AppendLine("            grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));");
            sb.AppendLine("            gap: 16px;");
            sb.AppendLine("            margin-bottom: 8px;");
            sb.AppendLine("        }");
            sb.AppendLine("        .overview-card {");
            sb.AppendLine("            background: rgba(255, 255, 255, 0.02);");
            sb.AppendLine("            border: 1px solid var(--border);");
            sb.AppendLine("            border-radius: 10px;");
            sb.AppendLine("            padding: 16px;");
            sb.AppendLine("            text-align: center;");
            sb.AppendLine("        }");
            sb.AppendLine("        .overview-card .num {");
            sb.AppendLine("            font-size: 2rem;");
            sb.AppendLine("            font-weight: bold;");
            sb.AppendLine("            color: var(--primary);");
            sb.AppendLine("            margin: 4px 0;");
            sb.AppendLine("        }");
            sb.AppendLine("        .overview-card .unit {");
            sb.AppendLine("            font-size: 0.85rem;");
            sb.AppendLine("            color: var(--text-secondary);");
            sb.AppendLine("        }");
            sb.AppendLine("        .charts-grid {");
            sb.AppendLine("            display: grid;");
            sb.AppendLine("            grid-template-columns: 2fr 1fr;");
            sb.AppendLine("            gap: 24px;");
            sb.AppendLine("            margin-bottom: 28px;");
            sb.AppendLine("        }");
            sb.AppendLine("        @media (max-width: 900px) {");
            sb.AppendLine("            .charts-grid {");
            sb.AppendLine("                grid-template-columns: 1fr;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        .chart-container-card {");
            sb.AppendLine("            margin-bottom: 0 !important;");
            sb.AppendLine("        }");
            sb.AppendLine("        .full-width-chart {");
            sb.AppendLine("            margin-bottom: 28px !important;");
            sb.AppendLine("        }");
            sb.AppendLine("        .chart-wrapper {");
            sb.AppendLine("            position: relative;");
            sb.AppendLine("            height: 350px;");
            sb.AppendLine("            width: 100%;");
            sb.AppendLine("        }");
            sb.AppendLine("        .macro-ratios-legend {");
            sb.AppendLine("            display: flex;");
            sb.AppendLine("            justify-content: space-around;");
            sb.AppendLine("            margin-top: 16px;");
            sb.AppendLine("            font-size: 0.9rem;");
            sb.AppendLine("        }");
            sb.AppendLine("        .macro-ratios-legend span {");
            sb.AppendLine("            display: flex;");
            sb.AppendLine("            align-items: center;");
            sb.AppendLine("            gap: 6px;");
            sb.AppendLine("        }");
            sb.AppendLine("        .legend-dot {");
            sb.AppendLine("            width: 12px;");
            sb.AppendLine("            height: 12px;");
            sb.AppendLine("            border-radius: 50%;");
            sb.AppendLine("            display: inline-block;");
            sb.AppendLine("        }");
            sb.AppendLine("        .simulator-card {");
            sb.AppendLine("            border-color: rgba(56, 189, 248, 0.3) !important;");
            sb.AppendLine("            background: linear-gradient(180deg, #151f32 0%, rgba(21, 31, 50, 0.4) 100%);");
            sb.AppendLine("        }");
            sb.AppendLine("        .simulator-controls {");
            sb.AppendLine("            display: flex;");
            sb.AppendLine("            flex-direction: column;");
            sb.AppendLine("            gap: 20px;");
            sb.AppendLine("        }");
            sb.AppendLine("        .slider-group {");
            sb.AppendLine("            background: rgba(255, 255, 255, 0.02);");
            sb.AppendLine("            border: 1px solid var(--border);");
            sb.AppendLine("            border-radius: 12px;");
            sb.AppendLine("            padding: 16px 20px;");
            sb.AppendLine("        }");
            sb.AppendLine("        .slider-label-row {");
            sb.AppendLine("            display: flex;");
            sb.AppendLine("            justify-content: space-between;");
            sb.AppendLine("            align-items: center;");
            sb.AppendLine("            margin-bottom: 12px;");
            sb.AppendLine("            font-weight: 500;");
            sb.AppendLine("        }");
            sb.AppendLine("        .custom-slider {");
            sb.AppendLine("            -webkit-appearance: none;");
            sb.AppendLine("            width: 100%;");
            sb.AppendLine("            height: 6px;");
            sb.AppendLine("            border-radius: 3px;");
            sb.AppendLine("            background: var(--border);");
            sb.AppendLine("            outline: none;");
            sb.AppendLine("            margin: 10px 0;");
            sb.AppendLine("        }");
            sb.AppendLine("        .custom-slider::-webkit-slider-thumb {");
            sb.AppendLine("            -webkit-appearance: none;");
            sb.AppendLine("            appearance: none;");
            sb.AppendLine("            width: 18px;");
            sb.AppendLine("            height: 18px;");
            sb.AppendLine("            border-radius: 50%;");
            sb.AppendLine("            background: var(--primary);");
            sb.AppendLine("            cursor: pointer;");
            sb.AppendLine("            box-shadow: 0 0 10px var(--primary);");
            sb.AppendLine("            transition: all 0.2s ease;");
            sb.AppendLine("        }");
            sb.AppendLine("        .custom-slider::-webkit-slider-thumb:hover {");
            sb.AppendLine("            transform: scale(1.2);");
            sb.AppendLine("        }");
            sb.AppendLine("        .presets-row {");
            sb.AppendLine("            display: flex;");
            sb.AppendLine("            flex-wrap: wrap;");
            sb.AppendLine("            gap: 12px;");
            sb.AppendLine("        }");
            sb.AppendLine("        .preset-btn {");
            sb.AppendLine("            background: rgba(255, 255, 255, 0.03);");
            sb.AppendLine("            border: 1px solid var(--border);");
            sb.AppendLine("            color: var(--text-secondary);");
            sb.AppendLine("            padding: 8px 16px;");
            sb.AppendLine("            border-radius: 8px;");
            sb.AppendLine("            font-size: 0.85rem;");
            sb.AppendLine("            cursor: pointer;");
            sb.AppendLine("            font-weight: 500;");
            sb.AppendLine("            transition: all 0.2s ease;");
            sb.AppendLine("        }");
            sb.AppendLine("        .preset-btn:hover {");
            sb.AppendLine("            border-color: var(--primary);");
            sb.AppendLine("            color: var(--text);");
            sb.AppendLine("            background: rgba(56, 189, 248, 0.05);");
            sb.AppendLine("        }");
            sb.AppendLine("        .preset-btn.active {");
            sb.AppendLine("            background: var(--primary);");
            sb.AppendLine("            color: #0b0f19;");
            sb.AppendLine("            border-color: var(--primary);");
            sb.AppendLine("            font-weight: bold;");
            sb.AppendLine("            box-shadow: 0 0 10px rgba(56, 189, 248, 0.3);");
            sb.AppendLine("        }");
            sb.AppendLine("        table {");
            sb.AppendLine("            width: 100%;");
            sb.AppendLine("            border-collapse: collapse;");
            sb.AppendLine("            margin-top: 12px;");
            sb.AppendLine("        }");
            sb.AppendLine("        th, td {");
            sb.AppendLine("            padding: 14px 18px;");
            sb.AppendLine("            text-align: left;");
            sb.AppendLine("            border-bottom: 1px solid var(--border);");
            sb.AppendLine("        }");
            sb.AppendLine("        th {");
            sb.AppendLine("            background-color: rgba(255, 255, 255, 0.015);");
            sb.AppendLine("            color: var(--text-secondary);");
            sb.AppendLine("            font-weight: 600;");
            sb.AppendLine("            font-size: 0.9rem;");
            sb.AppendLine("            text-transform: uppercase;");
            sb.AppendLine("            letter-spacing: 0.5px;");
            sb.AppendLine("        }");
            sb.AppendLine("        tr:hover {");
            sb.AppendLine("            background-color: rgba(255, 255, 255, 0.01);");
            sb.AppendLine("        }");
            sb.AppendLine("        .badge {");
            sb.AppendLine("            display: inline-block;");
            sb.AppendLine("            padding: 5px 12px;");
            sb.AppendLine("            border-radius: 9999px;");
            sb.AppendLine("            font-size: 0.75rem;");
            sb.AppendLine("            font-weight: bold;");
            sb.AppendLine("            text-transform: uppercase;");
            sb.AppendLine("            letter-spacing: 0.5px;");
            sb.AppendLine("        }");
            sb.AppendLine("        .badge-optimal {");
            sb.AppendLine("            background-color: rgba(16, 185, 129, 0.15);");
            sb.AppendLine("            color: var(--success);");
            sb.AppendLine("            border: 1px solid rgba(16, 185, 129, 0.3);");
            sb.AppendLine("        }");
            sb.AppendLine("        .badge-suboptimal {");
            sb.AppendLine("            background-color: rgba(245, 158, 11, 0.15);");
            sb.AppendLine("            color: var(--warning);");
            sb.AppendLine("            border: 1px solid rgba(245, 158, 11, 0.3);");
            sb.AppendLine("        }");
            sb.AppendLine("        .badge-deficit {");
            sb.AppendLine("            background-color: rgba(239, 68, 68, 0.15);");
            sb.AppendLine("            color: var(--danger);");
            sb.AppendLine("            border: 1px solid rgba(239, 68, 68, 0.3);");
            sb.AppendLine("        }");
            sb.AppendLine("        .progress-bar-container {");
            sb.AppendLine("            background: rgba(255, 255, 255, 0.05);");
            sb.AppendLine("            border-radius: 4px;");
            sb.AppendLine("            height: 8px;");
            sb.AppendLine("            width: 100%;");
            sb.AppendLine("            margin-top: 6px;");
            sb.AppendLine("            overflow: hidden;");
            sb.AppendLine("        }");
            sb.AppendLine("        .progress-bar {");
            sb.AppendLine("            height: 100%;");
            sb.AppendLine("            border-radius: 4px;");
            sb.AppendLine("            transition: width 0.3s ease, background-color 0.3s ease;");
            sb.AppendLine("        }");
            sb.AppendLine("        .progress-optimal { background-color: var(--success); }");
            sb.AppendLine("        .progress-suboptimal { background-color: var(--warning); }");
            sb.AppendLine("        .progress-deficit { background-color: var(--danger); }");
            sb.AppendLine("        .table-header-row {");
            sb.AppendLine("            display: flex;");
            sb.AppendLine("            justify-content: space-between;");
            sb.AppendLine("            align-items: center;");
            sb.AppendLine("            flex-wrap: wrap;");
            sb.AppendLine("            gap: 16px;");
            sb.AppendLine("            border-bottom: 2px solid var(--border);");
            sb.AppendLine("            padding-bottom: 12px;");
            sb.AppendLine("            margin-bottom: 20px;");
            sb.AppendLine("        }");
            sb.AppendLine("        .table-header-row h2 {");
            sb.AppendLine("            margin: 0;");
            sb.AppendLine("            border-bottom: none;");
            sb.AppendLine("            padding-bottom: 0;");
            sb.AppendLine("        }");
            sb.AppendLine("        .table-controls {");
            sb.AppendLine("            display: flex;");
            sb.AppendLine("            gap: 12px;");
            sb.AppendLine("            align-items: center;");
            sb.AppendLine("        }");
            sb.AppendLine("        .table-search-input {");
            sb.AppendLine("            background: rgba(255, 255, 255, 0.03);");
            sb.AppendLine("            border: 1px solid var(--border);");
            sb.AppendLine("            color: var(--text);");
            sb.AppendLine("            padding: 8px 14px;");
            sb.AppendLine("            border-radius: 8px;");
            sb.AppendLine("            font-size: 0.9rem;");
            sb.AppendLine("            outline: none;");
            sb.AppendLine("            width: 220px;");
            sb.AppendLine("            transition: all 0.2s ease;");
            sb.AppendLine("        }");
            sb.AppendLine("        .table-search-input:focus {");
            sb.AppendLine("            border-color: var(--primary);");
            sb.AppendLine("            box-shadow: 0 0 8px rgba(56, 189, 248, 0.2);");
            sb.AppendLine("        }");
            sb.AppendLine("        .table-filter-select {");
            sb.AppendLine("            background: #151f32;");
            sb.AppendLine("            border: 1px solid var(--border);");
            sb.AppendLine("            color: var(--text);");
            sb.AppendLine("            padding: 8px 14px;");
            sb.AppendLine("            border-radius: 8px;");
            sb.AppendLine("            font-size: 0.9rem;");
            sb.AppendLine("            outline: none;");
            sb.AppendLine("            cursor: pointer;");
            sb.AppendLine("            transition: all 0.2s ease;");
            sb.AppendLine("        }");
            sb.AppendLine("        .table-filter-select:focus {");
            sb.AppendLine("            border-color: var(--primary);");
            sb.AppendLine("        }");
            sb.AppendLine("        .empty-state {");
            sb.AppendLine("            color: var(--text-secondary);");
            sb.AppendLine("            font-style: italic;");
            sb.AppendLine("            padding: 16px 0;");
            sb.AppendLine("            text-align: center;");
            sb.AppendLine("        }");
            sb.AppendLine("        .footer {");
            sb.AppendLine("            text-align: center;");
            sb.AppendLine("            padding: 32px 0;");
            sb.AppendLine("            color: var(--text-secondary);");
            sb.AppendLine("            font-size: 0.85rem;");
            sb.AppendLine("            border-top: 1px solid var(--border);");
            sb.AppendLine("            margin-top: 48px;");
            sb.AppendLine("            line-height: 1.8;");
            sb.AppendLine("        }");
            sb.AppendLine("        @media (max-width: 768px) {");
            sb.AppendLine("            body { padding: 16px; }");
            sb.AppendLine("            .header h1 { font-size: 2rem; }");
            sb.AppendLine("            th, td { padding: 10px 12px; font-size: 0.85rem; }");
            sb.AppendLine("            .section-card { padding: 20px; }");
            sb.AppendLine("        }");
            sb.AppendLine("    </style>");
            sb.AppendLine("</head>");
            sb.AppendLine("<body>");
            sb.AppendLine("    <div class=\"container\">");
            sb.AppendLine("        ");
            sb.AppendLine("        <!-- Header -->");
            sb.AppendLine("        <div class=\"header\">");
            sb.AppendLine("            <h1>NUTRI-SCRIBE CLINICAL WEEKLY REPORT</h1>");
            sb.AppendLine("            <p>Automated Cumulative Baseline Performance & Diagnostic Food Summary</p>");
            sb.AppendLine("            <div class=\"meta-grid\">");
            sb.AppendLine("                <div class=\"meta-card\">");
            sb.AppendLine("                    <div class=\"label\">Timeframe</div>");
            sb.AppendLine($"                    <div class=\"value\">{StartDate} - {EndDate}</div>");
            sb.AppendLine("                </div>");
            sb.AppendLine("                <div class=\"meta-card\">");
            sb.AppendLine("                    <div class=\"label\">Clinical Target Profile</div>");
            sb.AppendLine($"                    <div class=\"value\">{ProfileName}</div>");
            sb.AppendLine("                </div>");
            sb.AppendLine("                <div class=\"meta-card\">");
            sb.AppendLine("                    <div class=\"label\">Patient Profile</div>");
            sb.AppendLine($"                    <div class=\"value\">{BiologicalSex}, {Age} yrs</div>");
            sb.AppendLine("                </div>");
            sb.AppendLine("                <div class=\"meta-card\">");
            sb.AppendLine("                    <div class=\"label\">Activity Index</div>");
            sb.AppendLine($"                    <div class=\"value\">{ActivityLevel}</div>");
            sb.AppendLine("                </div>");
            sb.AppendLine("            </div>");
            sb.AppendLine("        </div>");
            sb.AppendLine("        ");
            sb.AppendLine("        <!-- Section 1: Weekly Dashboard -->");
            sb.AppendLine("        <div class=\"section-card\">");
            sb.AppendLine("            <h2>📊 Weekly Clinical Dashboard (7-Day Average)</h2>");
            sb.AppendLine("            <div class=\"overview-grid\">");
            sb.AppendLine("                <div class=\"overview-card\">");
            sb.AppendLine("                    <div class=\"label\">Energy Intake</div>");
            sb.AppendLine($"                    <div class=\"num\">{AvgCalories:N0}</div>");
            sb.AppendLine("                    <div class=\"unit\">kcal / day</div>");
            sb.AppendLine("                </div>");
            sb.AppendLine("                <div class=\"overview-card\">");
            sb.AppendLine("                    <div class=\"label\">Protein Average</div>");
            sb.AppendLine($"                    <div class=\"num\">{AvgProtein:F1}</div>");
            sb.AppendLine("                    <div class=\"unit\">g / day</div>");
            sb.AppendLine("                </div>");
            sb.AppendLine("                <div class=\"overview-card\">");
            sb.AppendLine("                    <div class=\"label\">Carbohydrates</div>");
            sb.AppendLine($"                    <div class=\"num\">{AvgCarbs:F1}</div>");
            sb.AppendLine("                    <div class=\"unit\">g / day</div>");
            sb.AppendLine("                </div>");
            sb.AppendLine("                <div class=\"overview-card\">");
            sb.AppendLine("                    <div class=\"label\">Lipids (Fat)</div>");
            sb.AppendLine($"                    <div class=\"num\">{AvgFat:F1}</div>");
            sb.AppendLine("                    <div class=\"unit\">g / day</div>");
            sb.AppendLine("                </div>");
            sb.AppendLine("                <div class=\"overview-card\">");
            sb.AppendLine("                    <div class=\"label\">Hydration Average</div>");
            sb.AppendLine($"                    <div class=\"num\">{AvgWater:F0}</div>");
            sb.AppendLine("                    <div class=\"unit\">ml / day</div>");
            sb.AppendLine("                </div>");
            sb.AppendLine("            </div>");
            sb.AppendLine("        </div>");
            sb.AppendLine("        ");
            sb.AppendLine("        <!-- Section 2: Interactive Charts Visualizer Grid -->");
            sb.AppendLine("        <div class=\"charts-grid\">");
            sb.AppendLine("            <div class=\"section-card chart-container-card\">");
            sb.AppendLine("                <h2>📈 Caloric & Macronutrient Trends</h2>");
            sb.AppendLine("                <div class=\"chart-wrapper\">");
            sb.AppendLine("                    <canvas id=\"trendsChart\"></canvas>");
            sb.AppendLine("                </div>");
            sb.AppendLine("            </div>");
            sb.AppendLine("            ");
            sb.AppendLine("            <div class=\"section-card chart-container-card\">");
            sb.AppendLine("                <h2>🍕 Energy Contribution</h2>");
            sb.AppendLine("                <div class=\"chart-wrapper\">");
            sb.AppendLine("                    <canvas id=\"macrosDoughnutChart\"></canvas>");
            sb.AppendLine("                </div>");
            sb.AppendLine("                <div class=\"macro-ratios-legend\" id=\"macroRatiosLegend\"></div>");
            sb.AppendLine("            </div>");
            sb.AppendLine("        </div>");
            sb.AppendLine("        ");
            sb.AppendLine("        <div class=\"section-card chart-container-card full-width-chart\">");
            sb.AppendLine("            <h2>📊 Nutrient Intake vs RDA Targets</h2>");
            sb.AppendLine("            <div class=\"chart-wrapper\">");
            sb.AppendLine("                <canvas id=\"nutrientBarChart\"></canvas>");
            sb.AppendLine("            </div>");
            sb.AppendLine("        </div>");
            sb.AppendLine("        ");
            sb.AppendLine("        <!-- Section 3: Goal Target Adjustment Simulator -->");
            sb.AppendLine("        <div class=\"section-card simulator-card\">");
            sb.AppendLine("            <h2>⚙️ Clinical RDA Baseline Calibration Simulator</h2>");
            sb.AppendLine("            <p style=\"margin-top: -10px; margin-bottom: 20px; font-size: 0.9rem; color: var(--text-secondary);\">");
            sb.AppendLine("                Interactively scale target RDA values to simulate different protocol densities (e.g. Ketogenic, High Protein, or Caloric Deficit limits). This dynamically recalculates table progress states and updates interactive charts.");
            sb.AppendLine("            </p>");
            sb.AppendLine("            <div class=\"simulator-controls\">");
            sb.AppendLine("                <div class=\"slider-group\">");
            sb.AppendLine("                    <div class=\"slider-label-row\">");
            sb.AppendLine("                        <span>RDA Target Calibration Scale:</span>");
            sb.AppendLine("                        <span id=\"scaleValue\" style=\"color: var(--primary); font-weight: bold; font-size: 1.15rem;\">100% (Standard)</span>");
            sb.AppendLine("                    </div>");
            sb.AppendLine("                    <input type=\"range\" id=\"rdaScaleSlider\" min=\"50\" max=\"150\" value=\"100\" class=\"custom-slider\">");
            sb.AppendLine("                </div>");
            sb.AppendLine("                <div class=\"presets-row\">");
            sb.AppendLine("                    <button class=\"preset-btn active\" data-scale=\"100\">Standard Baseline</button>");
            sb.AppendLine("                    <button class=\"preset-btn\" data-scale=\"80\">Caloric Deficit Protocol (-20%)</button>");
            sb.AppendLine("                    <button class=\"preset-btn\" data-scale=\"120\">Mass Gaining Protocol (+20%)</button>");
            sb.AppendLine("                    <button class=\"preset-btn\" data-scale=\"150\">Clinical Intensive Load (+50%)</button>");
            sb.AppendLine("                </div>");
            sb.AppendLine("            </div>");
            sb.AppendLine("        </div>");
            sb.AppendLine("        ");
            sb.AppendLine("        <!-- Section 4: Comprehensive Nutrient Performance Table -->");
            sb.AppendLine("        <div class=\"section-card\">");
            sb.AppendLine("            <h2>📋 Weekly Nutrient Totals & Intake Averages</h2>");
            sb.AppendLine("            <table>");
            sb.AppendLine("                <thead>");
            sb.AppendLine("                    <tr>");
            sb.AppendLine("                        <th style=\"width: 25%;\">Nutrient</th>");
            sb.AppendLine("                        <th style=\"width: 20%;\">Group / Category</th>");
            sb.AppendLine("                        <th style=\"text-align: right; width: 15%;\">Daily Average</th>");
            sb.AppendLine("                        <th style=\"text-align: right; width: 15%;\">RDA Target</th>");
            sb.AppendLine("                        <th style=\"text-align: right; width: 10%;\">Met %</th>");
            sb.AppendLine("                        <th style=\"text-align: center; width: 15%;\">Status</th>");
            sb.AppendLine("                    </tr>");
            sb.AppendLine("                </thead>");
            sb.AppendLine("                <tbody>");
            
            foreach (var status in WeeklyNutrientStatuses)
            {
                string badgeClass = status.Status == StatusColor.GREEN ? "badge-optimal" :
                                   status.Status == StatusColor.YELLOW ? "badge-suboptimal" : "badge-deficit";
                
                string statusText = status.Status == StatusColor.GREEN ? "Optimal" :
                                   status.Status == StatusColor.YELLOW ? "Sub-Optimal" : 
                                   (status.Definition.IsMaxLimit ? "Exceeded" : "Deficient");
                
                string progressClass = status.Status == StatusColor.GREEN ? "progress-optimal" :
                                      status.Status == StatusColor.YELLOW ? "progress-suboptimal" : "progress-deficit";
                
                double progressWidth = Math.Min(status.Percentage, 100.0);
                
                sb.AppendLine($"                    <tr data-nutrient-key=\"{status.Definition.Key}\">");
                sb.AppendLine($"                        <td style=\"font-weight: 600;\">{System.Net.WebUtility.HtmlEncode(status.Definition.Name)}</td>");
                sb.AppendLine($"                        <td style=\"color: var(--text-secondary); font-size: 0.9rem;\">{System.Net.WebUtility.HtmlEncode(status.Definition.Group.GetDisplayName())}</td>");
                sb.AppendLine($"                        <td style=\"text-align: right; font-weight: 500;\">{status.Intake:F1} {status.Definition.Unit}</td>");
                sb.AppendLine($"                        <td class=\"nutrient-rda-val\" style=\"text-align: right; color: var(--text-secondary);\">{status.Definition.Rda:F1} {status.Definition.Unit}</td>");
                sb.AppendLine("                        <td style=\"text-align: right; font-weight: bold;\">");
                sb.AppendLine($"                            <span class=\"nutrient-pct-text\">{status.Percentage:F0}%</span>");
                sb.AppendLine("                            <div class=\"progress-bar-container\">");
                sb.AppendLine($"                                <div class=\"progress-bar {progressClass}\" style=\"width: {progressWidth:F0}%;\"></div>");
                sb.AppendLine("                            </div>");
                sb.AppendLine("                        </td>");
                sb.AppendLine($"                        <td style=\"text-align: center;\"><span class=\"badge {badgeClass}\">{statusText}</span></td>");
                sb.AppendLine("                    </tr>");
            }
            
            sb.AppendLine("                </tbody>");
            sb.AppendLine("            </table>");
            sb.AppendLine("        </div>");
            
            // Food Journal Summary Section
            sb.AppendLine("        <div class=\"section-card\">");
            sb.AppendLine("            <div class=\"table-header-row\">");
            sb.AppendLine("                <h2>🥗 Food Log Journal Summary</h2>");
            sb.AppendLine("                <div class=\"table-controls\">");
            sb.AppendLine("                    <input type=\"text\" id=\"foodSearch\" placeholder=\"🔍 Search food logs...\" class=\"table-search-input\">");
            sb.AppendLine("                    <select id=\"mealFilter\" class=\"table-filter-select\">");
            sb.AppendLine("                        <option value=\"all\">All Meals</option>");
            sb.AppendLine("                        <option value=\"Breakfast\">Breakfast</option>");
            sb.AppendLine("                        <option value=\"Lunch\">Lunch</option>");
            sb.AppendLine("                        <option value=\"Dinner\">Dinner</option>");
            sb.AppendLine("                        <option value=\"Snack\">Snacks</option>");
            sb.AppendLine("                    </select>");
            sb.AppendLine("                </div>");
            sb.AppendLine("            </div>");
            
            if (WeeklyFoodLogs == null || WeeklyFoodLogs.Count == 0)
            {
                sb.AppendLine("            <p class=\"empty-state\">No food logs recorded for this timeframe.</p>");
            }
            else
            {
                sb.AppendLine("            <table>");
                sb.AppendLine("                <thead>");
                sb.AppendLine("                    <tr>");
                sb.AppendLine("                        <th style=\"width: 15%;\">Date</th>");
                sb.AppendLine("                        <th style=\"width: 20%;\">Meal Category</th>");
                sb.AppendLine("                        <th style=\"width: 45%;\">Food Item / Description</th>");
                sb.AppendLine("                        <th style=\"text-align: right; width: 20%;\">Logged Quantity</th>");
                sb.AppendLine("                    </tr>");
                sb.AppendLine("                </thead>");
                sb.AppendLine("                <tbody id=\"foodLogsTableBody\">");
                
                foreach (var food in WeeklyFoodLogs.OrderBy(f => f.Date))
                {
                    sb.AppendLine($"                    <tr class=\"food-log-row\" data-food-name=\"{System.Net.WebUtility.HtmlEncode(food.FoodName)}\" data-meal-type=\"{food.MealType}\">");
                    sb.AppendLine($"                        <td style=\"color: var(--text-secondary); font-size: 0.95rem;\">{food.Date}</td>");
                    sb.AppendLine($"                        <td style=\"font-weight: 500;\">{System.Net.WebUtility.HtmlEncode(food.MealType)}</td>");
                    sb.AppendLine($"                        <td>{System.Net.WebUtility.HtmlEncode(food.FoodName)}</td>");
                    sb.AppendLine($"                        <td style=\"text-align: right; font-weight: bold;\">{food.Quantity:F1} {System.Net.WebUtility.HtmlEncode(food.Unit)}</td>");
                    sb.AppendLine("                    </tr>");
                }
                
                sb.AppendLine("                    <tr id=\"logsEmptyState\" style=\"display: none;\">");
                sb.AppendLine("                        <td colspan=\"4\" class=\"empty-state\" style=\"text-align: center; padding: 24px;\">No matching food logs found for current filter.</td>");
                sb.AppendLine("                    </tr>");
                
                sb.AppendLine("                </tbody>");
                sb.AppendLine("            </table>");
            }
            
            sb.AppendLine("        </div>");
            
            // Footer
            sb.AppendLine("        <div class=\"footer\">");
            sb.AppendLine($"            Report compiled automatically by <strong>NutriScribe Clinical Daily & Weekly Suite</strong> on {DateTime.Now:MMMM dd, yyyy} at {DateTime.Now:hh:mm tt}");
            sb.AppendLine("            <br>");
            sb.AppendLine("            <strong>Medical Disclaimer:</strong> This automated software compilation provides qualitative intake comparisons based on current user configuration guidelines. It does not replace medical diagnostics or clinical nutritional counseling.");
            sb.AppendLine("            <br>");
            sb.AppendLine("            <em>CONFIDENTIALITY NOTICE: All data is securely processed locally and resides exclusively on-device.</em>");
            sb.AppendLine("        </div>");
            sb.AppendLine("        ");
            sb.AppendLine("    </div>");
            
            // Client-side JavaScript & Data payload
            sb.AppendLine("    <script>");
            
            // Generate foodLogs JSON
            sb.AppendLine("        const foodLogs = [");
            foreach (var log in WeeklyFoodLogs)
            {
                double calories = log.Calories;
                double protein = log.Nutrients.ContainsKey("protein") ? log.Nutrients["protein"] * log.Quantity : 0.0;
                double carbs = log.Nutrients.ContainsKey("carbohydrates") ? log.Nutrients["carbohydrates"] * log.Quantity : 0.0;
                double fat = log.Nutrients.ContainsKey("fat") ? log.Nutrients["fat"] * log.Quantity : 0.0;
                double water = log.Nutrients.ContainsKey("water") ? log.Nutrients["water"] * log.Quantity : 0.0;
                
                sb.AppendLine("            {");
                sb.AppendLine($"                date: \"{log.Date}\",");
                sb.AppendLine($"                foodName: \"{System.Net.WebUtility.HtmlEncode(log.FoodName)}\",");
                sb.AppendLine($"                mealType: \"{log.MealType}\",");
                sb.AppendLine($"                quantity: {log.Quantity},");
                sb.AppendLine($"                calories: {calories},");
                sb.AppendLine($"                protein: {protein},");
                sb.AppendLine($"                carbs: {carbs},");
                sb.AppendLine($"                fat: {fat},");
                sb.AppendLine($"                water: {water}");
                sb.AppendLine("            },");
            }
            sb.AppendLine("        ];");
            
            // Generate nutrientStatuses JSON
            sb.AppendLine("        const nutrientStatuses = [");
            foreach (var status in WeeklyNutrientStatuses)
            {
                sb.AppendLine("            {");
                sb.AppendLine($"                key: \"{status.Definition.Key}\",");
                sb.AppendLine($"                name: \"{System.Net.WebUtility.HtmlEncode(status.Definition.Name)}\",");
                sb.AppendLine($"                group: \"{System.Net.WebUtility.HtmlEncode(status.Definition.Group.GetDisplayName())}\",");
                sb.AppendLine($"                intake: {status.Intake},");
                sb.AppendLine($"                rda: {status.Definition.Rda},");
                sb.AppendLine($"                percentage: {status.Percentage},");
                sb.AppendLine($"                isMaxLimit: {(status.Definition.IsMaxLimit ? "true" : "false")},");
                sb.AppendLine($"                unit: \"{System.Net.WebUtility.HtmlEncode(status.Definition.Unit)}\"");
                sb.AppendLine("            },");
            }
            sb.AppendLine("        ];");
            
            // JavaScript rendering and Chart orchestration
            sb.AppendLine("        // Parse Timeframe Limits");
            sb.AppendLine($"        const sDate = new Date(\"{StartDate}\");");
            sb.AppendLine($"        const eDate = new Date(\"{EndDate}\");");
            sb.AppendLine("        ");
            sb.AppendLine("        // Generate exact 7-day timeline dates");
            sb.AppendLine("        const dates = [];");
            sb.AppendLine("        let current = new Date(sDate);");
            sb.AppendLine("        while (current <= eDate) {");
            sb.AppendLine("            dates.push(current.toISOString().split('T')[0]);");
            sb.AppendLine("            current.setDate(current.getDate() + 1);");
            sb.AppendLine("        }");
            sb.AppendLine("        if (dates.length > 7) dates.length = 7; // Clamp to 7");
            sb.AppendLine("        if (dates.length === 0) {");
            sb.AppendLine("            // Fallback list from data");
            sb.AppendLine("            dates.push(...[...new Set(foodLogs.map(l => l.date))].sort());");
            sb.AppendLine("        }");
            sb.AppendLine("        ");
            sb.AppendLine("        // Aggregate values by day");
            sb.AppendLine("        const dailyTotals = dates.map(dateStr => {");
            sb.AppendLine("            const logsOnDay = foodLogs.filter(l => l.date === dateStr);");
            sb.AppendLine("            const calories = logsOnDay.reduce((sum, l) => sum + l.calories, 0);");
            sb.AppendLine("            const protein = logsOnDay.reduce((sum, l) => sum + l.protein, 0);");
            sb.AppendLine("            const carbs = logsOnDay.reduce((sum, l) => sum + l.carbs, 0);");
            sb.AppendLine("            const fat = logsOnDay.reduce((sum, l) => sum + l.fat, 0);");
            sb.AppendLine("            const water = logsOnDay.reduce((sum, l) => sum + l.water, 0);");
            sb.AppendLine("            return { date: dateStr, calories, protein, carbs, fat, water };");
            sb.AppendLine("        });");
            sb.AppendLine("        ");
            sb.AppendLine("        // Chart 1: Daily Trends");
            sb.AppendLine("        const ctxTrends = document.getElementById('trendsChart').getContext('2d');");
            sb.AppendLine("        const trendsChart = new Chart(ctxTrends, {");
            sb.AppendLine("            type: 'line',");
            sb.AppendLine("            data: {");
            sb.AppendLine("                labels: dailyTotals.map(d => {");
            sb.AppendLine("                    const dt = new Date(d.date + 'T00:00:00');");
            sb.AppendLine("                    return dt.toLocaleDateString('en-US', { weekday: 'short', day: 'numeric' });");
            sb.AppendLine("                }),");
            sb.AppendLine("                datasets: [");
            sb.AppendLine("                    {");
            sb.AppendLine("                        label: 'Calories (kcal)',");
            sb.AppendLine("                        data: dailyTotals.map(d => d.calories),");
            sb.AppendLine("                        borderColor: '#38bdf8',");
            sb.AppendLine("                        backgroundColor: 'rgba(56, 189, 248, 0.1)',");
            sb.AppendLine("                        yAxisID: 'yCalories',");
            sb.AppendLine("                        tension: 0.3,");
            sb.AppendLine("                        borderWidth: 3,");
            sb.AppendLine("                        pointBackgroundColor: '#38bdf8'");
            sb.AppendLine("                    },");
            sb.AppendLine("                    {");
            sb.AppendLine("                        label: 'Protein (g)',");
            sb.AppendLine("                        data: dailyTotals.map(d => d.protein),");
            sb.AppendLine("                        borderColor: '#10b981',");
            sb.AppendLine("                        backgroundColor: 'transparent',");
            sb.AppendLine("                        yAxisID: 'yMacros',");
            sb.AppendLine("                        tension: 0.3,");
            sb.AppendLine("                        borderWidth: 2,");
            sb.AppendLine("                        pointBackgroundColor: '#10b981'");
            sb.AppendLine("                    },");
            sb.AppendLine("                    {");
            sb.AppendLine("                        label: 'Carbohydrates (g)',");
            sb.AppendLine("                        data: dailyTotals.map(d => d.carbs),");
            sb.AppendLine("                        borderColor: '#f59e0b',");
            sb.AppendLine("                        backgroundColor: 'transparent',");
            sb.AppendLine("                        yAxisID: 'yMacros',");
            sb.AppendLine("                        tension: 0.3,");
            sb.AppendLine("                        borderWidth: 2,");
            sb.AppendLine("                        pointBackgroundColor: '#f59e0b'");
            sb.AppendLine("                    },");
            sb.AppendLine("                    {");
            sb.AppendLine("                        label: 'Fat (g)',");
            sb.AppendLine("                        data: dailyTotals.map(d => d.fat),");
            sb.AppendLine("                        borderColor: '#ef4444',");
            sb.AppendLine("                        backgroundColor: 'transparent',");
            sb.AppendLine("                        yAxisID: 'yMacros',");
            sb.AppendLine("                        tension: 0.3,");
            sb.AppendLine("                        borderWidth: 2,");
            sb.AppendLine("                        pointBackgroundColor: '#ef4444'");
            sb.AppendLine("                    }");
            sb.AppendLine("                ]");
            sb.AppendLine("            },");
            sb.AppendLine("            options: {");
            sb.AppendLine("                responsive: true,");
            sb.AppendLine("                maintainAspectRatio: false,");
            sb.AppendLine("                plugins: {");
            sb.AppendLine("                    legend: {");
            sb.AppendLine("                        position: 'top',");
            sb.AppendLine("                        labels: { color: '#94a3b8', font: { family: \"'Segoe UI', sans-serif\" } }");
            sb.AppendLine("                    },");
            sb.AppendLine("                    tooltip: {");
            sb.AppendLine("                        backgroundColor: '#151f32',");
            sb.AppendLine("                        titleColor: '#f8fafc',");
            sb.AppendLine("                        bodyColor: '#e2e8f0',");
            sb.AppendLine("                        borderColor: '#24354f',");
            sb.AppendLine("                        borderWidth: 1,");
            sb.AppendLine("                        padding: 12");
            sb.AppendLine("                    }");
            sb.AppendLine("                },");
            sb.AppendLine("                scales: {");
            sb.AppendLine("                    x: {");
            sb.AppendLine("                        grid: { color: '#1e293b' },");
            sb.AppendLine("                        ticks: { color: '#94a3b8' }");
            sb.AppendLine("                    },");
            sb.AppendLine("                    yCalories: {");
            sb.AppendLine("                        type: 'linear',");
            sb.AppendLine("                        display: true,");
            sb.AppendLine("                        position: 'left',");
            sb.AppendLine("                        title: { display: true, text: 'Energy (kcal)', color: '#38bdf8' },");
            sb.AppendLine("                        grid: { color: '#1e293b' },");
            sb.AppendLine("                        ticks: { color: '#94a3b8' }");
            sb.AppendLine("                    },");
            sb.AppendLine("                    yMacros: {");
            sb.AppendLine("                        type: 'linear',");
            sb.AppendLine("                        display: true,");
            sb.AppendLine("                        position: 'right',");
            sb.AppendLine("                        title: { display: true, text: 'Macros (g)', color: '#10b981' },");
            sb.AppendLine("                        grid: { drawOnChartArea: false },");
            sb.AppendLine("                        ticks: { color: '#94a3b8' }");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        });");
            sb.AppendLine("        ");
            sb.AppendLine("        // Chart 2: Macronutrient Energy Contribution");
            sb.AppendLine($"        const avgProtein = {AvgProtein};");
            sb.AppendLine($"        const avgCarbs = {AvgCarbs};");
            sb.AppendLine($"        const avgFat = {AvgFat};");
            sb.AppendLine("        ");
            sb.AppendLine("        const pKcal = avgProtein * 4;");
            sb.AppendLine("        const cKcal = avgCarbs * 4;");
            sb.AppendLine("        const fKcal = avgFat * 9;");
            sb.AppendLine("        const totalKcal = pKcal + cKcal + fKcal;");
            sb.AppendLine("        ");
            sb.AppendLine("        const pPercent = totalKcal > 0 ? (pKcal / totalKcal) * 100 : 0;");
            sb.AppendLine("        const cPercent = totalKcal > 0 ? (cKcal / totalKcal) * 100 : 0;");
            sb.AppendLine("        const fPercent = totalKcal > 0 ? (fKcal / totalKcal) * 100 : 0;");
            sb.AppendLine("        ");
            sb.AppendLine("        document.getElementById('macroRatiosLegend').innerHTML = `");
            sb.AppendLine("            <span><span class=\"legend-dot\" style=\"background-color: #10b981;\"></span> Protein: ${pPercent.toFixed(1)}%</span>");
            sb.AppendLine("            <span><span class=\"legend-dot\" style=\"background-color: #f59e0b;\"></span> Carbs: ${cPercent.toFixed(1)}%</span>");
            sb.AppendLine("            <span><span class=\"legend-dot\" style=\"background-color: #ef4444;\"></span> Fat: ${fPercent.toFixed(1)}%</span>");
            sb.AppendLine("        `;");
            sb.AppendLine("        ");
            sb.AppendLine("        const ctxMacros = document.getElementById('macrosDoughnutChart').getContext('2d');");
            sb.AppendLine("        const macrosChart = new Chart(ctxMacros, {");
            sb.AppendLine("            type: 'doughnut',");
            sb.AppendLine("            data: {");
            sb.AppendLine("                labels: ['Protein (kcal)', 'Carbohydrates (kcal)', 'Fat (kcal)'],");
            sb.AppendLine("                datasets: [{");
            sb.AppendLine("                    data: [pKcal.toFixed(1), cKcal.toFixed(1), fKcal.toFixed(1)],");
            sb.AppendLine("                    backgroundColor: ['#10b981', '#f59e0b', '#ef4444'],");
            sb.AppendLine("                    borderColor: '#151f32',");
            sb.AppendLine("                    borderWidth: 2");
            sb.AppendLine("                }]");
            sb.AppendLine("            },");
            sb.AppendLine("            options: {");
            sb.AppendLine("                responsive: true,");
            sb.AppendLine("                maintainAspectRatio: false,");
            sb.AppendLine("                plugins: {");
            sb.AppendLine("                    legend: { display: false },");
            sb.AppendLine("                    tooltip: {");
            sb.AppendLine("                        backgroundColor: '#151f32',");
            sb.AppendLine("                        titleColor: '#f8fafc',");
            sb.AppendLine("                        bodyColor: '#e2e8f0',");
            sb.AppendLine("                        borderColor: '#24354f',");
            sb.AppendLine("                        borderWidth: 1,");
            sb.AppendLine("                        callbacks: {");
            sb.AppendLine("                            label: function(context) {");
            sb.AppendLine("                                const val = context.raw;");
            sb.AppendLine("                                const pct = totalKcal > 0 ? (val / totalKcal * 100).toFixed(1) : 0;");
            sb.AppendLine("                                return `${context.label}: ${parseFloat(val).toFixed(0)} kcal (${pct}%)`;");
            sb.AppendLine("                            }");
            sb.AppendLine("                        }");
            sb.AppendLine("                    }");
            sb.AppendLine("                },");
            sb.AppendLine("                cutout: '70%'");
            sb.AppendLine("            }");
            sb.AppendLine("        });");
            sb.AppendLine("        ");
            sb.AppendLine("        // Chart 3: Intake vs RDA Target Baseline Comparison");
            sb.AppendLine("        const keysToShow = [\"calories\", \"protein\", \"carbohydrates\", \"fat\", \"water\", \"calcium\", \"iron\", \"sodium\", \"vitamin_c\"];");
            sb.AppendLine("        const barNutrients = nutrientStatuses.filter(s => keysToShow.includes(s.key.toLowerCase()));");
            sb.AppendLine("        ");
            sb.AppendLine("        const ctxBar = document.getElementById('nutrientBarChart').getContext('2d');");
            sb.AppendLine("        const nutrientBarChart = new Chart(ctxBar, {");
            sb.AppendLine("            type: 'bar',");
            sb.AppendLine("            data: {");
            sb.AppendLine("                labels: barNutrients.map(s => s.name + ' (' + s.unit + ')'),");
            sb.AppendLine("                datasets: [");
            sb.AppendLine("                    {");
            sb.AppendLine("                        label: 'Average Daily Intake',");
            sb.AppendLine("                        data: barNutrients.map(s => s.intake),");
            sb.AppendLine("                        backgroundColor: '#38bdf8',");
            sb.AppendLine("                        borderColor: '#38bdf8',");
            sb.AppendLine("                        borderWidth: 1,");
            sb.AppendLine("                        borderRadius: 4");
            sb.AppendLine("                    },");
            sb.AppendLine("                    {");
            sb.AppendLine("                        label: 'RDA Target Limit',");
            sb.AppendLine("                        data: barNutrients.map(s => s.rda),");
            sb.AppendLine("                        backgroundColor: 'rgba(255, 255, 255, 0.08)',");
            sb.AppendLine("                        borderColor: '#94a3b8',");
            sb.AppendLine("                        borderWidth: 1,");
            sb.AppendLine("                        borderDash: [5, 5],");
            sb.AppendLine("                        borderRadius: 4");
            sb.AppendLine("                    }");
            sb.AppendLine("                ]");
            sb.AppendLine("            },");
            sb.AppendLine("            options: {");
            sb.AppendLine("                indexAxis: 'y',");
            sb.AppendLine("                responsive: true,");
            sb.AppendLine("                maintainAspectRatio: false,");
            sb.AppendLine("                plugins: {");
            sb.AppendLine("                    legend: {");
            sb.AppendLine("                        position: 'top',");
            sb.AppendLine("                        labels: { color: '#94a3b8', font: { family: \"'Segoe UI', sans-serif\" } }");
            sb.AppendLine("                    },");
            sb.AppendLine("                    tooltip: {");
            sb.AppendLine("                        backgroundColor: '#151f32',");
            sb.AppendLine("                        titleColor: '#f8fafc',");
            sb.AppendLine("                        bodyColor: '#e2e8f0',");
            sb.AppendLine("                        borderColor: '#24354f',");
            sb.AppendLine("                        borderWidth: 1,");
            sb.AppendLine("                        callbacks: {");
            sb.AppendLine("                            afterBody: function(context) {");
            sb.AppendLine("                                const index = context[0].dataIndex;");
            sb.AppendLine("                                const s = barNutrients[index];");
            sb.AppendLine("                                const currentRda = s.rda * (currentMultiplier / 100);");
            sb.AppendLine("                                const pct = currentRda > 0 ? (s.intake / currentRda * 100).toFixed(0) : 0;");
            sb.AppendLine("                                return `Progress: ${pct}% of Calibrated Target`;");
            sb.AppendLine("                            }");
            sb.AppendLine("                        }");
            sb.AppendLine("                    }");
            sb.AppendLine("                },");
            sb.AppendLine("                scales: {");
            sb.AppendLine("                    x: {");
            sb.AppendLine("                        grid: { color: '#1e293b' },");
            sb.AppendLine("                        ticks: { color: '#94a3b8' }");
            sb.AppendLine("                    },");
            sb.AppendLine("                    y: {");
            sb.AppendLine("                        grid: { display: false },");
            sb.AppendLine("                        ticks: { color: '#f8fafc', font: { weight: 'bold' } }");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        });");
            sb.AppendLine("        ");
            sb.AppendLine("        // Dynamic Goal Calibration Engine");
            sb.AppendLine("        let currentMultiplier = 100;");
            sb.AppendLine("        const rdaSlider = document.getElementById('rdaScaleSlider');");
            sb.AppendLine("        const scaleValueText = document.getElementById('scaleValue');");
            sb.AppendLine("        const presetBtns = document.querySelectorAll('.preset-btn');");
            sb.AppendLine("        ");
            sb.AppendLine("        function updateRdaScale(multiplier) {");
            sb.AppendLine("            currentMultiplier = multiplier;");
            sb.AppendLine("            rdaSlider.value = multiplier;");
            sb.AppendLine("            ");
            sb.AppendLine("            let suffix = \" (Standard)\";");
            sb.AppendLine("            if (multiplier < 100) suffix = ` (${100 - multiplier}% Deficit Protocol)`;");
            sb.AppendLine("            if (multiplier > 100) suffix = ` (+${multiplier - 100}% Loading Protocol)`;");
            sb.AppendLine("            scaleValueText.textContent = `${multiplier}%${suffix}`;");
            sb.AppendLine("            ");
            sb.AppendLine("            presetBtns.forEach(btn => {");
            sb.AppendLine("                if (parseInt(btn.dataset.scale) === multiplier) {");
            sb.AppendLine("                    btn.classList.add('active');");
            sb.AppendLine("                } else {");
            sb.AppendLine("                    btn.classList.remove('active');");
            sb.AppendLine("                }");
            sb.AppendLine("            });");
            sb.AppendLine("            ");
            sb.AppendLine("            // Update HTML cells dynamically");
            sb.AppendLine("            nutrientStatuses.forEach(s => {");
            sb.AppendLine("                const row = document.querySelector(`tr[data-nutrient-key=\"${s.key}\"]`);");
            sb.AppendLine("                if (row) {");
            sb.AppendLine("                    const scaledRda = s.rda * (multiplier / 100);");
            sb.AppendLine("                    const rdaCell = row.querySelector('.nutrient-rda-val');");
            sb.AppendLine("                    if (rdaCell) {");
            sb.AppendLine("                        rdaCell.textContent = scaledRda.toFixed(1) + \" \" + s.unit;");
            sb.AppendLine("                    }");
            sb.AppendLine("                    ");
            sb.AppendLine("                    const pct = scaledRda > 0 ? (s.intake / scaledRda * 100) : 0;");
            sb.AppendLine("                    const pctTextCell = row.querySelector('.nutrient-pct-text');");
            sb.AppendLine("                    if (pctTextCell) {");
            sb.AppendLine("                        pctTextCell.textContent = pct.toFixed(0) + \"%\";");
            sb.AppendLine("                    }");
            sb.AppendLine("                    ");
            sb.AppendLine("                    const progressBar = row.querySelector('.progress-bar');");
            sb.AppendLine("                    if (progressBar) {");
            sb.AppendLine("                        progressBar.style.width = Math.min(pct, 100.0).toFixed(0) + \"%\";");
            sb.AppendLine("                        progressBar.className = \"progress-bar\";");
            sb.AppendLine("                        if (s.isMaxLimit) {");
            sb.AppendLine("                            if (s.intake > scaledRda && scaledRda > 0) progressBar.classList.add('progress-deficit');");
            sb.AppendLine("                            else progressBar.classList.add('progress-optimal');");
            sb.AppendLine("                        } else {");
            sb.AppendLine("                            if (pct < 50) progressBar.classList.add('progress-deficit');");
            sb.AppendLine("                            else if (pct < 100) progressBar.classList.add('progress-suboptimal');");
            sb.AppendLine("                            else progressBar.classList.add('progress-optimal');");
            sb.AppendLine("                        }");
            sb.AppendLine("                    }");
            sb.AppendLine("                    ");
            sb.AppendLine("                    const badge = row.querySelector('.badge');");
            sb.AppendLine("                    if (badge) {");
            sb.AppendLine("                        badge.className = \"badge\";");
            sb.AppendLine("                        let statusText = \"Optimal\";");
            sb.AppendLine("                        if (s.isMaxLimit) {");
            sb.AppendLine("                            if (s.intake > scaledRda && scaledRda > 0) {");
            sb.AppendLine("                                statusText = \"Exceeded\";");
            sb.AppendLine("                                badge.classList.add('badge-deficit');");
            sb.AppendLine("                            } else {");
            sb.AppendLine("                                badge.classList.add('badge-optimal');");
            sb.AppendLine("                            }");
            sb.AppendLine("                        } else {");
            sb.AppendLine("                            if (pct < 50) {");
            sb.AppendLine("                                statusText = \"Deficient\";");
            sb.AppendLine("                                badge.classList.add('badge-deficit');");
            sb.AppendLine("                            } else if (pct < 100) {");
            sb.AppendLine("                                statusText = \"Sub-Optimal\";");
            sb.AppendLine("                                badge.classList.add('badge-suboptimal');");
            sb.AppendLine("                            } else {");
            sb.AppendLine("                                badge.classList.add('badge-optimal');");
            sb.AppendLine("                            }");
            sb.AppendLine("                        }");
            sb.AppendLine("                        badge.textContent = statusText;");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            });");
            sb.AppendLine("            ");
            sb.AppendLine("            // Update bar chart data limit bar dynamically");
            sb.AppendLine("            nutrientBarChart.data.datasets[1].data = barNutrients.map(s => s.rda * (multiplier / 100));");
            sb.AppendLine("            nutrientBarChart.update();");
            sb.AppendLine("        }");
            sb.AppendLine("        ");
            sb.AppendLine("        rdaSlider.addEventListener('input', (e) => {");
            sb.AppendLine("            updateRdaScale(parseInt(e.target.value));");
            sb.AppendLine("        });");
            sb.AppendLine("        ");
            sb.AppendLine("        presetBtns.forEach(btn => {");
            sb.AppendLine("            btn.addEventListener('click', () => {");
            sb.AppendLine("                updateRdaScale(parseInt(btn.dataset.scale));");
            sb.AppendLine("            });");
            sb.AppendLine("        });");
            sb.AppendLine("        ");
            sb.AppendLine("        // Food Logs Interactive Live Filtering");
            sb.AppendLine("        const foodSearchInput = document.getElementById('foodSearch');");
            sb.AppendLine("        const mealFilterSelect = document.getElementById('mealFilter');");
            sb.AppendLine("        const logRows = document.querySelectorAll('.food-log-row');");
            sb.AppendLine("        ");
            sb.AppendLine("        function filterFoodLogs() {");
            sb.AppendLine("            const query = foodSearchInput.value.toLowerCase().trim();");
            sb.AppendLine("            const mealType = mealFilterSelect.value;");
            sb.AppendLine("            let visibleCount = 0;");
            sb.AppendLine("            ");
            sb.AppendLine("            logRows.forEach(row => {");
            sb.AppendLine("                const name = row.dataset.foodName.toLowerCase();");
            sb.AppendLine("                const meal = row.dataset.mealType;");
            sb.AppendLine("                const matchesQuery = name.includes(query);");
            sb.AppendLine("                const matchesMeal = mealType === 'all' || meal === mealType;");
            sb.AppendLine("                ");
            sb.AppendLine("                if (matchesQuery && matchesMeal) {");
            sb.AppendLine("                    row.style.display = '';");
            sb.AppendLine("                    visibleCount++;");
            sb.AppendLine("                } else {");
            sb.AppendLine("                    row.style.display = 'none';");
            sb.AppendLine("                }");
            sb.AppendLine("            });");
            sb.AppendLine("            ");
            sb.AppendLine("            const emptyState = document.getElementById('logsEmptyState');");
            sb.AppendLine("            if (emptyState) {");
            sb.AppendLine("                if (visibleCount === 0) {");
            sb.AppendLine("                    emptyState.style.display = '';");
            sb.AppendLine("                } else {");
            sb.AppendLine("                    emptyState.style.display = 'none';");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        ");
            sb.AppendLine("        if (foodSearchInput) foodSearchInput.addEventListener('input', filterFoodLogs);");
            sb.AppendLine("        if (mealFilterSelect) mealFilterSelect.addEventListener('change', filterFoodLogs);");
            sb.AppendLine("    </script>");
            sb.AppendLine("</body>");
            sb.AppendLine("</html>");

            return sb.ToString();
        }
    }
}
